### ISSUE TITLE
Restore GLASS ambiguity of the original?

### ISSUE THREAD

**Issue by jpcompton** [heasm66/Craverly-Heights_ZIL#9]
Frankly I *like* the fact that your implementation assumes that "glass" refers to the magnifying glass, but you've worked to mirror a lot of the quirks of the original and so might want to know that Craverly Prime instead does:

```
>get all
magnifying glass: Taken.
framed photo: Taken.
pair of sunglasses: Taken.
handgun: Taken.

>examine glass
Which do you mean, the pair of sunglasses or the magnifying glass?
```

**Comment by heasm66** [comment]
Actually I think you played the z3-version. In the other it works as in the original. The reason for this is that in z3 there are only 4 synonyms allowed per object and the sunglasses have: sunglasses, shades, glasses, shade & glass in the original. For the z3 I removed the last one for the reasons you wrote and that it seemed to be the less likely one you would use for the sunglasses. Have you tried it in the other versions?

**Comment by jpcompton** [comment]
Quite right, it does work in z5, I hadn't considered that it might be part of the fewer-synonyms workaround. Will remember to specify the Z-version in any other reports.
